# Generated by Django 5.0.7 on 2024-07-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingLanguageWebsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='react',
            name='name',
        ),
        migrations.AddField(
            model_name='react',
            name='description',
            field=models.CharField(max_length=500, null='Desription'),
            preserve_default='Desription',
        ),
        migrations.AddField(
            model_name='react',
            name='info',
            field=models.CharField(max_length=500, null='Info'),
            preserve_default='Info',
        ),
        migrations.AddField(
            model_name='react',
            name='language',
            field=models.CharField(max_length=30, null='Language'),
            preserve_default='Language',
        ),
    ]
