# Generated by Django 5.0.7 on 2024-07-15 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmingLanguageWebsite', '0002_remove_react_detail_remove_react_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='info',
        ),
    ]
