# Generated by Django 5.0.7 on 2024-07-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingLanguageWebsite', '0003_remove_react_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='description',
            field=models.CharField(max_length=500, null='Description'),
        ),
    ]
