# Generated by Django 5.0.7 on 2024-07-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmingLanguageWebsite', '0004_alter_react_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestingReact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30, null='Language')),
                ('applications', models.CharField(max_length=500, null='Description')),
            ],
        ),
    ]
