# Generated by Django 5.0.7 on 2024-07-16 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmingLanguageWebsite', '0005_interestingreact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interestingreact',
            old_name='language',
            new_name='programmingLanguage',
        ),
    ]
